"""Short greetings for a fresh research conversation."""

STARTUP_GREETINGS = (
    "Welcome back. What needs a closer look?",
    "Bring a question. We'll bring the objections.",
    "A good idea can survive a difficult question.",
    "Let's see what holds up under scrutiny.",
    "What's the decision behind today's research?",
    "Big idea? Start with the awkward question.",
    "Let's make the assumptions earn their keep.",
    "What would change your mind about this idea?",
    "A blank page is cheaper than a bad plan.",
    "Today: fewer assumptions, better questions.",
    "Hope is allowed. Evidence gets the last word.",
    "Tell us the plan before reality reviews it.",
    "Which problem is costing you the most?",
    "Let's find the catch before the customer does.",
    "What deserves your time, money, or doubt?",
    "Ambition is welcome. So are constraints.",
    "Before we build it, who would pay for it?",
    "What's promising, and what might break?",
    "Let's turn a hunch into something testable.",
    "A confident answer still needs evidence.",
    "The budget would like a word.",
    "Which unknown is worth resolving first?",
    "Tell us what success would actually look like.",
    "Small pilot. Clear criteria. Then we talk.",
    "Let's give the idea a fair, difficult hearing.",
    "The spreadsheet would like to meet a customer.",
    "What's the smallest useful experiment?",
    "Bring the context. Keep the assumptions handy.",
    "Let's check the bridge before crossing it.",
    "What are we trying to learn, exactly?",
    "Good questions travel further than good slides.",
    "Let's meet the inconvenient facts early.",
    "Research first. Victory lap later.",
    "What's the downside if this goes wrong?",
    "Your idea has an appointment with the evidence.",
    "Let's ask the question the pitch deck skipped.",
    "The plan can be bold. The numbers must behave.",
    "Which claim needs more than a straight face?",
    "Welcome back. What needs a second opinion?",
    "Before the grand launch, one modest test.",
    "What should we understand before committing?",
    "Let's look for the reason this might not work.",
    "A useful answer should change a decision.",
    "What does the idea look like without optimism?",
    "Which trade-off are we avoiding?",
    "Good plans leave room for bad news.",
    "Let's put the obvious answer on trial.",
    "Researchers have ideas. Critics have questions.",
    "MB has the clipboard. RB and JB have questions.",
    "RB builds the case. JB checks the weak spots.",
    "Set the brief. Let the team argue usefully.",
    "The critics are awake. What's the proposal?",
    "What would make this worth doing?",
    "Let's replace 'probably' with a useful test.",
    "Bring the messy version. That's enough to start.",
    "What do we know, and what are we guessing?",
    "Welcome aboard. Which rabbit hole today?",
    "How deep does this question go?",
    "Let's see what lies below the first answer.",
    "No treasure map? A clear question will do.",
)
